In [15]:
import numpy as np
import pandas as pd
import pystan
import datetime
import sys
import os
from scipy.stats import norm, multivariate_normal
from codebase.file_utils import save_obj, load_obj

from codebase.plot import * 
from codebase.file_utils import save_obj, load_obj

%matplotlib inline

%load_ext autoreload
%autoreload 2

<img src='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAABHNCSVQICAgIfAhkiAAAAAlwSFlz
AAAB+wAAAfsBxc2miwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA6zSURB
VHic7ZtpeFRVmsf/5966taWqUlUJ2UioBBJiIBAwCZtog9IOgjqACsogKtqirT2ttt069nQ/zDzt
tI4+CrJIREFaFgWhBXpUNhHZQoKBkIUASchWla1S+3ar7r1nPkDaCAnZKoQP/D7mnPOe9/xy76n3
nFSAW9ziFoPFNED2LLK5wcyBDObkb8ZkxuaoSYlI6ZcOKq1eWFdedqNzGHQBk9RMEwFAASkk0Xw3
ETacDNi2vtvc7L0ROdw0AjoSotQVkKSvHQz/wRO1lScGModBFbDMaNRN1A4tUBCS3lk7BWhQkgpD
lG4852/+7DWr1R3uHAZVQDsbh6ZPN7CyxUrCzJMRouusj0ipRwD2uKm0Zn5d2dFwzX1TCGhnmdGo
G62Nna+isiUqhkzuKrkQaJlPEv5mFl2fvGg2t/VnzkEV8F5ioioOEWkLG86fvbpthynjdhXYZziQ
x1hC9J2NFyi8vCTt91Fh04KGip0AaG9zuCk2wQCVyoNU3Hjezee9bq92duzzTmxsRJoy+jEZZZYo
GTKJ6SJngdJqAfRzpze0+jHreUtPc7gpBLQnIYK6BYp/uGhw9YK688eu7v95ysgshcg9qSLMo3JC
4jqLKQFBgdKDPoQ+Pltb8dUyQLpeDjeVgI6EgLIQFT5tEl3rn2losHVsexbZ3EyT9wE1uGdkIPcy
BGxn8QUq1QrA5nqW5i2tLqvrrM9NK6AdkVIvL9E9bZL/oyfMVd/jqvc8LylzRBKDJSzIExwhQzuL
QYGQj4rHfFTc8mUdu3E7yoLtbTe9gI4EqVgVkug2i5+uXGo919ixbRog+3fTbQ8qJe4ZOYNfMoTI
OoshUNosgO60AisX15aeI2PSIp5KiFLI9ubb1vV3Qb2ltwLakUCDAkWX7/nHKRmmGIl9VgYsUhJm
2NXjKYADtM1ygne9QQDIXlk49FBstMKx66D1v4+XuQr7vqTe0VcBHQlRWiOCbmmSYe2SqtL6q5rJ
zsTb7lKx3FKOYC4DoqyS/B5bvLPxvD9Qtf6saxYLQGJErmDOdOMr/zo96km1nElr8bmPOBwI9COv
HnFPRIwmkSOv9kcAS4heRsidOkpeWBgZM+UBrTFAXNYL5Vf2ii9c1trNzpYdaoVil3WIc+wdk+gQ
noie3ecCcxt9ITcLAPWt/laGEO/9U6PmzZkenTtsSMQ8uYywJVW+grCstAvCIaAdArAsIWkRDDs/
KzLm2YcjY1Lv0UdW73HabE9n6V66cxSzfEmuJssTpKGVp+0vHq73FwL46eOjpMpbRAnNmJFrGJNu
Ukf9Yrz+3rghiumCKNXXWPhLYcjxGsIpoCMsIRoFITkW8AuyM8jC1+/QLx4bozCEJIq38+1rtpR6
V/yzb8eBlRb3fo5l783N0CWolAzJHaVNzkrTzlEp2bQ2q3TC5gn6wpnoQAmwSiGh2GitnTmVMc5O
UyfKWUKCIsU7+fZDKwqdT6DDpvkzAX4/+AMFjk0tDp5GRXLpQ2MUmhgDp5gxQT8+Y7hyPsMi8uxF
71H0oebujHALECjFKaW9Lm68n18wXp2kVzIcABytD5iXFzg+WVXkegpAsOOYziqo0OkK76GyquC3
ltZAzMhhqlSNmmWTE5T6e3IN05ITFLM4GdN0vtZ3ob8Jh1NAKXFbm5PtLU/eqTSlGjkNAJjdgn/N
aedXa0tdi7+t9G0FIF49rtMSEgAs1kDLkTPO7ebm4IUWeyh1bKomXqlgMG6kJmHcSM0clYLJ8XtR
1GTnbV3F6I5wCGikAb402npp1h1s7LQUZZSMIfALFOuL3UUrfnS8+rez7v9qcold5tilgHbO1fjK
9ubb17u9oshxzMiUBKXWqJNxd+fqb0tLVs4lILFnK71H0Ind7uiPgACVcFJlrb0tV6DzxqqTIhUM
CwDf1/rrVhTa33/3pGPxJYdQ2l2cbgVcQSosdx8uqnDtbGjh9SlDVSMNWhlnilfqZk42Th2ZpLpf
xrHec5e815zrr0dfBZSwzkZfqsv+1FS1KUknUwPARVvItfKUY+cn57yP7qv07UE3p8B2uhUwLk09
e0SCOrK+hbdYHYLjRIl71wWzv9jpEoeOHhGRrJAzyEyNiJuUqX0g2sBN5kGK6y2Blp5M3lsB9Qh4
y2Ja6x6+i0ucmKgwMATwhSjdUu49tKrQ/pvN5d53ml2CGwCmJipmKjgmyuaXzNeL2a0AkQ01Th5j
2DktO3Jyk8f9vcOBQHV94OK+fPumJmvQHxJoWkaKWq9Vs+yUsbq0zGT1I4RgeH2b5wef7+c7bl8F
eKgoHVVZa8ZPEORzR6sT1BzDUAD/d9F78e2Tzv99v8D+fLVTqAKAsbGamKey1Mt9Ann4eH3gTXTz
idWtAJ8PQWOk7NzSeQn/OTHDuEikVF1R4z8BQCy+6D1aWRfY0tTGG2OM8rRoPaeIj5ZHzJxszElN
VM8K8JS5WOfv8mzRnQAKoEhmt8gyPM4lU9SmBK1MCQBnW4KONT86v1hZ1PbwSXPw4JWussVjtH9Y
NCoiL9UoH/6PSu8jFrfY2t36erQHXLIEakMi1SydmzB31h3GGXFDFNPaK8Rme9B79Ixrd0WN+1ij
NRQ/doRmuFLBkHSTOm5GruG+pFjFdAmorG4IXH1Qua6ASniclfFtDYt+oUjKipPrCQB7QBQ2lrgP
fFzm+9XWUtcqJ3/5vDLDpJ79XHZk3u8nGZ42qlj1+ydtbxysCezrydp6ugmipNJ7WBPB5tydY0jP
HaVNzs3QzeE4ZpTbI+ZbnSFPbVOw9vsfnVvqWnirPyCNGD08IlqtYkh2hjZ5dErEQzoNm+6ykyOt
Lt5/PQEuSRRKo22VkydK+vvS1XEKlhCJAnsqvcVvH7f/ZU2R67eXbMEGAMiIV5oWZWiWvz5Fv2xG
sjqNJQRvn3Rs2lji/lNP19VjAQDgD7FHhujZB9OGqYxRkZxixgRDVlqS6uEOFaJUVu0rPFzctrnF
JqijImVp8dEKVWyUXDk92zAuMZ6bFwpBU1HrOw6AdhQgUooChb0+ItMbWJitSo5Ws3IAOGEOtL53
0vHZih9sC4vtofZ7Qu6523V/fmGcds1TY3V36pUsBwAbSlxnVh2xLfAD/IAIMDf7XYIkNmXfpp2l
18rkAJAy9HKFaIr/qULkeQQKy9zf1JgDB2uaeFNGijo5QsUyacNUUTOnGO42xSnv4oOwpDi1zYkc
efUc3I5Gk6PhyTuVKaOGyLUAYPGIoY9Pu/atL/L92+4q9wbflRJ2Trpm/jPjdBtfnqB/dIThcl8A
KG7hbRuKnb8qsQsVvVlTrwQAQMUlf3kwJI24Z4JhPMtcfng5GcH49GsrxJpGvvHIaeem2ma+KSjQ
lIwUdYyCY8j4dE1KzijNnIP2llF2wcXNnsoapw9XxsgYAl6k+KzUXbi2yP3KR2ecf6z3BFsBICdW
nvnIaG3eHybqX7vbpEqUMT+9OL4Qpe8VON7dXuFd39v19FoAABRVePbGGuXTszO0P7tu6lghUonE
llRdrhArLvmKdh9u29jcFiRRkfLUxBiFNiqSU9icoZQHo5mYBI1MBgBH6wMNb+U7Pnw337H4gi1Y
ciWs+uks3Z9fztUvfzxTm9Ne8XXkvQLHNytOOZeiD4e0PgkAIAYCYknKUNUDSXEKzdWNpnil7r4p
xqkjTarZMtk/K8TQ6Qve78qqvXurGwIJqcOUKfUWHsm8KGvxSP68YudXq4pcj39X49uOK2X142O0
Tz5/u/7TVybqH0rSya6ZBwD21/gubbrgWdDgEOx9W

In [2]:
# def gen_data_factor(nsim_data, rho =0.5, random_seed=None):
#     if random_seed is not None:
#         np.random.seed(random_seed)

#     alpha = np.array([1, 2, .3, -.8, 1, -1.4])
#     Lambda = np.array([[1,0], [.2, 0],[.6,0],[0,1], [0,.5], [0,.8]], dtype=float)
#     sigma_z = np.array([1.2, .7])
#     Phi_corr = np.eye(2)
#     Phi_corr[0,1] = rho
#     Phi_corr[1,0] = rho
#     Phi = np.diag(sigma_z) @ Phi_corr @  np.diag(sigma_z)

#     sigma_e = np.array([1, 1.2, .9, .8, 1, 1.4])
#     Theta = np.diag(sigma_e**2)

#     Marg_cov = Lambda @ Phi @ Lambda.T + Theta
#     yy = multivariate_normal.rvs(mean = alpha, cov=Marg_cov, size=nsim_data)

#     data = dict()
#     data['N'] = nsim_data
#     data['K'] = 2
#     data['J'] = 6
#     data['alpha'] = alpha
#     data['Lambda'] = Lambda
#     data['sigma_z'] = sigma_z
#     data['Phi_corr'] = Phi_corr
#     data['Phi'] = Phi
#     data['Marg_cov'] = Marg_cov
#     data['Theta'] = Theta
#     data['sigma_e'] = sigma_e
#     data['y'] = yy

#     return(data)

# data = gen_data(10)

In [73]:
def gen_data(nsim_data, rho =0.5, random_seed=None):
    if random_seed is not None:
        np.random.seed(random_seed)

    alpha = np.array([2, -.8,])
    sigma = np.array([1.2, .7])
    Phi_corr = np.eye(2)
#     Phi_corr[0,1] = rho
#     Phi_corr[1,0] = rho
    Phi = np.diag(sigma) @ Phi_corr @  np.diag(sigma)

    yy = multivariate_normal.rvs(mean = alpha, cov=Phi, size=nsim_data)

    data = dict()
    data['N'] = nsim_data
    data['K'] = 2
    data['alpha'] = alpha
    data['sigma'] = sigma
    data['Phi_corr'] = Phi_corr
    data['Phi'] = Phi
    data['y'] = yy
    data['sigma_prior'] = np.diag(np.linalg.inv(np.cov(data['y'], rowvar=False)))


    return(data)

data = gen_data(100)
data

{'N': 100,
 'K': 2,
 'alpha': array([ 2. , -0.8]),
 'sigma': array([1.2, 0.7]),
 'Phi_corr': array([[1., 0.],
        [0., 1.]]),
 'Phi': array([[1.44, 0.  ],
        [0.  , 0.49]]),
 'y': array([[ 1.91264787, -0.45192726],
        [ 1.13059899, -1.24183246],
        [ 2.37928859,  0.34350168],
        [ 1.12562462, -0.93298976],
        [ 3.16995197, -0.56545736],
        [ 1.99159622, -0.70818933],
        [-0.44772253, -0.81886599],
        [ 1.48878284, -1.35703455],
        [ 0.89350068, -1.03100695],
        [ 0.39263896, -0.02764292],
        [ 3.23993521, -0.38106545],
        [ 2.45440731, -1.99441655],
        [ 2.70913323, -1.64911678],
        [ 2.92278506,  0.14512978],
        [ 1.72935066, -0.34735904],
        [ 0.97874981,  0.95106358],
        [ 2.87746788, -0.38603752],
        [ 4.41488535, -1.87901559],
        [ 1.32777695, -2.22738379],
        [ 2.91366967, -1.7348699 ],
        [ 1.32140894,  0.24546995],
        [ 2.1582981 , -0.59992068],
        [ 2.64672909

In [74]:
mean = np.mean(data['y'], axis=0)
sigma = np.std(data['y'], axis=0)
# np.std(data['y']/ sigma - mean, axis=0)
np.std((data['y'] - mean)/sigma, axis=0)

array([1., 1.])

In [75]:
np.mean((data['y'] - mean)/sigma, axis=0)

array([-5.62883073e-16, -2.79776202e-16])

In [103]:
with open('./codebase/stan_code/cont/CFA/model0_center.stan', 'r') as file:
    model_code = file.read()
print(model_code)

data {
  int<lower=1> N;
  int<lower=1> K;
  matrix[N,K] yy;
  vector[K] sigma_prior;

}

transformed data{
  cov_matrix[K] I = diag_matrix(rep_vector(1, K));
  vector[K] zeros = rep_vector(0, K);
  real<lower=0> c0 = 2.5;
}

parameters {
  // cholesky_factor_corr[K] Phi_corr_chol;
  // vector<lower=0>[K] sigma_square;
  vector<lower=0>[K] sigma;
  vector[K] alpha;
}

transformed parameters{
  matrix[N,K] yy_centered ;
  for (n in 1:N){
    for (k in 1:K){
      // yy_centered[n,k] =  (yy[n,k] - alpha[k]) / sqrt(sigma_square[k]);  
      yy_centered[n,k] =  (yy[n,k] - alpha[k]) / sigma[k];
    }
  }
}

model {
  alpha ~ normal(0, 10);
  // for(k in 1:K) sigma_square[k] ~ inv_gamma(c0, (c0-1)/sigma_prior[k]);
  sigma ~ cauchy(0,.1);
  for (n in 1:N){
    // yy_centered[n, ] ~ multi_normal_cholesky(zeros, I);
    yy_centered[n, ] ~ multi_normal(zeros, I);

  }
}

// generated quantities{
//   matrix [K, K] Phi_cov = multiply_lower_tri_self_transpose(diag_pre_multiply(sigma, Phi_corr_chol

In [104]:
# model_code = """
# data {
#   int<lower=1> N;
#   int<lower=1> K;
#   matrix[N,K] yy;
# }

# transformed data{
#   cov_matrix[K] I = diag_matrix(rep_vector(1, K));
#   vector[K] zeros = rep_vector(0, K);
# }

# parameters {
#   vector<lower=0>[K] sigma;
#   vector[K] alpha;
# }

# transformed parameters{
#   matrix[N,K] yy_centered ;
#   for (n in 1:N){
#     for (k in 1:K){
#       yy_centered[n,k] =  (yy[n,k] - alpha[k]) / sigma[k];  
#     }
#   }
# }

# model {
#   to_vector(alpha) ~ normal(0, 10);
#   sigma ~ cauchy(0,2);
#   to_vector(yy_centered) ~ normal(0, 1);
# }

# """


In [105]:
sm = pystan.StanModel(model_code=model_code)

INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_6dd5bd6234e53216ed492c2a7a08c914 NOW.


In [106]:
stan_data = dict(N = data['N'], K = data['K'], yy = data['y'], sigma_prior = data['sigma_prior'])

In [107]:
fit = sm.sampling(data=stan_data, iter=3000, chains=1)

In [108]:
print(fit)

Inference for Stan model: anon_model_6dd5bd6234e53216ed492c2a7a08c914.
1 chains, each with iter=3000; warmup=1500; thin=1; 
post-warmup draws per chain=1500, total post-warmup draws=1500.

                       mean se_mean     sd   2.5%     25%     50%     75%  97.5%  n_eff   Rhat
sigma[1]             482.05  251.72 4074.4   7.43   23.27   48.24   128.9 1455.9    262   1.01
sigma[2]             155.46   23.45 728.89    4.5   14.51   37.25  100.13 1009.9    966    1.0
alpha[1]               1.65    0.36   5.73 -11.58   -0.72     1.9    4.24  12.91    261    1.0
alpha[2]              -0.57    0.23   4.93  -11.6   -2.48   -0.64    1.26  11.18    451    1.0
yy_centered[1,1]    -1.1e-3  3.4e-3   0.08  -0.16   -0.05  2.2e-4    0.05   0.16    545    1.0
yy_centered[2,1]      -0.03  4.4e-3   0.08  -0.22   -0.08   -0.02    0.02   0.13    369    1.0
yy_centered[3,1]       0.01  3.4e-3   0.08  -0.14   -0.03  7.7e-3    0.06   0.18    559    1.0
yy_centered[4,1]      -0.03  4.4e-3   0.08  -0.22  

In [109]:
ps= fit.extract(permuted=False, pars=['alpha', 'sigma'])  # return a dictionary of arrays
ps['alpha']

array([[[ -8.25741884,  -1.47613844]],

       [[ -9.31722372,  -6.64388347]],

       [[-14.94802954,  -3.73475661]],

       ...,

       [[  2.69386621,  -2.24858707]],

       [[  2.67062044,  -2.20480086]],

       [[  3.77011012,  -4.46718108]]])

In [110]:
ps['alpha'] = np.squeeze(ps['alpha'])
ps['sigma'] = np.squeeze(ps['sigma'])

In [111]:
%%opts Layout [fig_size=200]
plots = []

for k in range(data['K']):
    plots.append(plot_trace(ps['alpha'][:,k],
         true_value=data['alpha'][k],
         title = 'Posterior distribution for mean(%s)'%(k)).\
                 options(fig_inches=8, aspect=3))
layout = hv.Layout(plots).options(show_title = True,
                              vspace = .3,
                              absolute_scaling=False,
                              normalize=False) # use same y-range for all plots?

layout.cols(2)


:Layout
   .Overlay.Posterior_distribution_for_mean_left_parenthesis_0_right_parenthesis :Overlay
      .Curve.Samples    :Curve   [x]   (y)
      .Curve.True_Value :Curve   [x]   (y)
   .Overlay.Posterior_distribution_for_mean_left_parenthesis_1_right_parenthesis :Overlay
      .Curve.Samples    :Curve   [x]   (y)
      .Curve.True_Value :Curve   [x]   (y)

In [112]:
%%opts Layout [fig_size=200]
plots = []

for k in range(data['K']):
    plots.append(plot_trace(ps['sigma'][:,k],
         true_value=data['sigma'][k],
         title = 'Posterior distribution for mean(%s)'%(k)).\
                 options(fig_inches=8, aspect=3))
layout = hv.Layout(plots).options(show_title = True,
                              vspace = .3,
                              absolute_scaling=False,
                              normalize=False) # use same y-range for all plots?

layout.cols(2)


:Layout
   .Overlay.Posterior_distribution_for_mean_left_parenthesis_0_right_parenthesis :Overlay
      .Curve.Samples    :Curve   [x]   (y)
      .Curve.True_Value :Curve   [x]   (y)
   .Overlay.Posterior_distribution_for_mean_left_parenthesis_1_right_parenthesis :Overlay
      .Curve.Samples    :Curve   [x]   (y)
      .Curve.True_Value :Curve   [x]   (y)